/*
 * Buffer scoring AI, autogenerated scores
 *
 * Copyright (C) 2014 Lauri Kasanen   All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef MAGIC_H
#define MAGIC_H

#define input0w 0.257753
#define input0b -0.019608
#define input1w 2.965236
#define input1b 0.388235
#define input2w 0.392745
#define input2b 0.835294
#define hidden0w0 -0.835294
#define hidden0w1 -0.563726
#define hidden0w2 0.137255
#define hidden0b -0.162745
#define hidden1w0 0.764706
#define hidden1w1 0.780392
#define hidden1w2 0.145098
#define hidden1b 0.338235
#define hidden2w0 0.011765
#define hidden2w1 0.584314
#define hidden2w2 -0.607843
#define hidden2b 0.932941
#define hidden3w0 0.035294
#define hidden3w1 0.799020
#define hidden3w2 0.647059
#define hidden3b -0.960784
#define hidden4w0 0.968627
#define hidden4w1 -0.304902
#define hidden4w2 0.592157
#define hidden4b -0.367647
#define hidden5w0 0.462632
#define hidden5w1 -0.490196
#define hidden5w2 0.665686
#define hidden5b -0.160784
#define hidden6w0 -0.215686
#define hidden6w1 0.411765
#define hidden6w2 0.807408
#define hidden6b 0.048039
#define hidden7w0 0.033333
#define hidden7w1 -0.976471
#define hidden7w2 0.380392
#define hidden7b 0.377299
#define outputw0 -0.164706
#define outputw1 -0.965294
#define outputw2 0.422549
#define outputw3 0.796651
#define outputw4 -0.918235
#define outputw5 0.973769
#define outputw6 0.529217
#define outputw7 0.499020
#define outputb 0.247348

#endif
